picscape/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

# Views
from . import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.RootRedirectView.as_view(), name='root_redirect'),
    path('', include(('posts.urls','posts'), namespace ='posts')),
    path('', include(('users.urls','users'), namespace ='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platzigram/urls.py
"""Platzigram URLs module."""

# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include(('posts.urls','posts'), namespace ='posts')),
    path('users/',include(('users.urls','users'), namespace ='users'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [

    path(
        route='feed/',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),
    path(
        route='p/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    path(
        route='p/new/',
        view=views.CreatePostView.as_view(),
        name='create'
    ),
    path(
        route='l/<int:pk>/',
        view=views.LikeView.as_view(),
        name='like'
    ),
  
]

posts/models.py
# Django
from django.db import models
from django.contrib.auth.models import User

# Utilities
from uuid import uuid4
import os


def picture_upload_path(instance, filename):
    """
    Return the path to the post picture.
    """
    username = instance.user.username
    extension = filename.split('.')[-1]
    unique_filename = f"{username}-{uuid4()}.{extension}"
    return os.path.join('posts', 'photos', unique_filename)


class Post(models.Model):
    """
    Post model.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    
    title = models.CharField(max_length=255)

    photo = models.ImageField(upload_to=picture_upload_path)

    created = models.DateTimeField(auto_now_add=True)

    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """
        Return title and username.
        """
        return '{} by @{}'.format(self.title, self.user.username)
        

class Likes(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')

    def __str__(self):
        """
        Return username and title.
        """
        return '{} likes {}'.format(self.user.username, self.post.title)

posts/views.py
# Django
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, RedirectView
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404

# Models
from posts.models import Post, Likes


class PostsFeedView(LoginRequiredMixin, ListView):
    """
    Return all published posts
    """
    model = Post
    paginate_by = 5
    ordering = ('-created')
    context_object_name = 'posts'
    template_name = 'posts/feed.html'

    def get_context_data(self, **kwargs):
        """
        Add post's likes to context
        """
        context = super().get_context_data(**kwargs)
        for post in context['posts']:
            post.likes_count = post.likes.count()
            post.is_liking = post.likes.filter(
                user=self.request.user
            ).exists()
        return context


class PostDetailView(LoginRequiredMixin, DetailView):
    """
    Return post detail.
    """
    template_name = 'posts/detail.html'
    model = Post
    context_object_name = 'post'
    slug_field = 'pk'
    slug_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        """
        Add post's likes to context
        """
        context = super().get_context_data(**kwargs)
        context['likes_count'] = self.get_object().likes.count()
        context['is_liking'] = self.get_object().likes.filter(
            user=self.request.user
        ).exists()
        return context


class CreatePostView(LoginRequiredMixin, CreateView):
    """
    Create a new post.
    """
    model = Post
    template_name = 'posts/new.html'
    fields = [
        'title',
        'photo'
    ]

    def form_valid(self, form):
        """
        Validate form.
        """
        form.instance.user = self.request.user
        form.save()
        return super(CreatePostView, self).form_valid(form)

    def get_success_url(self):
        """
        Return to post's feed.
        """
        return reverse('posts:detail', kwargs={'pk': self.object.pk})
        

class LikeView(LoginRequiredMixin, RedirectView):
    """
    Like or unlike a post.
    """
    pattern_name = 'posts:detail'
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        pk = kwargs['pk']
        post = get_object_or_404(Post, pk=pk)
        user = self.request.user

        # Check if the user is already liking the post
        like_exists = Likes.objects.filter(
            user=user,
            post=post,
        ).exists()

        if like_exists:
            # If already liking, unlike
            Likes.objects.filter(
                user=user,
                post=post,
            ).delete()
        else:
            # If not liking, like
            Likes.objects.create(
                user=user,
                post=post,
            )

        return super().get_redirect_url(*args, **kwargs)

templates/posts/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>{{ post.title }} | PicScape</title>
{% endblock %}

{% block container %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
                <div class="media pt-3 pl-3 pb-1">
                    <a href="{% url 'users:detail' post.user.username %}"> 
                        <img class="mr-3 rounded-circle"height="35"src="{{ post.user.profile.picture.url }}"alt="{{ post.user.get_full_name }}">
                    </a>
                    <div class="media-body">
                        <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
                    </div>
                </div>

                <img style="width: 100%;"src="{{ post.photo.url }}"alt="{{ post.title }}">

                <p class="mt-1 ml-2" >
                    <a href="{% url 'posts:like' post.pk %}" style="color: #000; font-size: 20px;">
                        {% if is_liking %}
                            <i class="fa fa-heart" style="color: red;"></i>
                        {% else %}
                            <i class="far fa-heart" style="color: black;"></i>
                        {% endif %}
                    </a> {{ likes_count }} likes
                </p>
                <p class="ml-2 mt-0 mb-2">
                    <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>PicScape</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">
            {% if not posts %}
                <div class="col-12 mt-5">
                    <h2 class="text-center">No posts yet</h2>
                </div>
            {% endif %}
            {% for post in posts %}
                {% include "posts/post.html"%}
            {% endfor %}
        </div>
    </div>
    <nav>
        <ul class="pagination justify-content-end">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    Previous
                </a>
            </li>
            {% endif %}
            {% if posts %}
            <li class="page-item">
                <a class="page-link" href="#">
                    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    Next
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/posts/new.html
{% extends "base.html" %}

{% block head_content %}
    <title>Create new post</title>
{% endblock %}

{% block container %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Post a new photo!</h4>

                <form method="POST" enctype="multipart/form-data">
                    
                    {% csrf_token %}

                    {# Title field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %} is-invalid {% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                            value="{% if form.errors %} {{ form.title.value }} {% endif %}"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %} is-invalid {% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %} 
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/posts/post.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="{% url 'users:detail' post.user.username %}">
            <img class="mr-3 rounded-circle" height="35" src="{{ post.user.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
        </div>
    </div>
  
    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">
  
    <p class="mt-1 ml-2" >
        <a href="{% url 'posts:like' post.pk %}" style="color: #000; font-size: 20px;">
            {% if post.is_liking %}
                <i class="fa fa-heart" style="color: red;"></i>
            {% else %}
                <i class="far fa-heart" style="color: black;"></i>
            {% endif %}
        </a> {{ post.likes_count }} Likes
    </p>
    <p class="ml-2 mt-0 mb-2">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
    </p>
  </div>

templates/posts/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="{% url 'users:detail' post.user.username %}">
            <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
        </div>
    </div>
  
    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">
  
    <p class="mt-1 ml-2" >
        <a href="" style="color: #000; font-size: 20px;">
            <i class="far fa-heart"></i>
        </a> {{post.likes}}
    </p>
    <p class="ml-2 mt-0 mb-2">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
    </p>
  </div>