picscape/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

# Views
from . import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.RootRedirectView.as_view(), name='root_redirect'),
    path('', include(('posts.urls','posts'), namespace ='posts')),
    path('', include(('users.urls','users'), namespace ='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platzigram/urls.py
"""Platzigram URLs module."""

# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include(('posts.urls','posts'), namespace ='posts')),
    path('users/',include(('users.urls','users'), namespace ='users'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [

    path(
        route='feed/',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),
    path(
        route='p/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    path(
        route='p/new/',
        view=views.CreatePostView.as_view(),
        name='create'
    ),
    path(
        route='l/<int:pk>/',
        view=views.LikeView.as_view(),
        name='like'
    ),
  
]

users/urls.py
# Django
from django.urls import path

# View
from users import views

urlpatterns = [

    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/',
        view=views.ProfileUpdateView.as_view(),
        name='profile'
    ),

    # Profiles
    path(
        route='u/<str:username>/',
        view=views.ProfileDetailView.as_view(),
        name='detail'
    ),
    path(
        route='f/<str:username>/',
        view=views.FollowView.as_view(),
        name='follow'
    ),

]

users/models.py
# Django
from django.contrib.auth.models import User
from django.db import models

# Utilities
import os


def picture_upload_path(instance, filename):
    """
    Return the path to the profile picture.
    """
    username = instance.user.username
    extension = filename.split('.')[-1]
    unique_filename = f"{username}.{extension}"
    return os.path.join('users', 'pictures', unique_filename)

class Profile(models.Model):
    """
    Profile model.
    Proxy model that extends the base data with other information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)

    biography = models.TextField(blank=True)

    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to=picture_upload_path,
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)

    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """
        Return username.
        """
        return self.user.username


class Follows(models.Model):

    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')

    followee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Return username of both.
        """
        return f"{self.follower} follows {self.followee}"

users/forms.py
# Django
from django import forms
from django.contrib.auth.models import User

# Models
from users.models import Profile


class SignupForm(forms.Form):
    """
    Signup Form.
    """

    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput(),
    )

    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput(),
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean(self):  
        """
        Verify password confirmation match.
        """
        data = super().clean() 
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError("Passwords don't match")

        return data

    def clean_username(self):
        """
        Username must be unique.
        """
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use')
        return username

    def save(self): 
        """
        Create user and profile
        """
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.views.generic import DetailView, FormView, UpdateView, RedirectView
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404

# Models
from django.contrib.auth.models import User
from posts.models import Post
from users.models import Profile, Follows

# Forms
from users.forms import SignupForm


class LoginView(auth_views.LoginView):
    """
    Users login view.
    """
    template_name = 'users/login.html'
    next_page = 'posts:feed'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """
    Users logout view.
    """
    next_page = 'users:login'


class SignupView(FormView):
    """
    Users sign up view.
    """
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        """
        This method is called when valid form data has been POSTed.
        """
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        """
        Return to login page.
        """
        return reverse('users:login')


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    """
    Update profile view.
    """
    template_name = 'users/profile.html'
    model = Profile
    fields = [
        'website', 
        'biography', 
        'phone_number', 
        'picture'
    ]

    def get_object(self):
        """
        Return user's profile.
        """
        return self.request.user.profile

    def get_success_url(self):
        """
        Return to user's profile.
        """
        username = self.object.user.username
        return reverse(
            'users:detail', 
            kwargs={
                'username': username,
            }
        )


class ProfileDetailView(LoginRequiredMixin, DetailView):
    """
    User detail view.
    """
    template_name = 'users/detail.html'
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username' 
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """
        Add user's posts to context
        """
        context = super().get_context_data(**kwargs)
        followee = self.get_object()
        follower = self.request.user

        context['is_following'] = Follows.objects.filter(
            follower=follower,
            followee=followee,
        ).exists()

        context['posts'] = self.get_object().posts.all()
        context['posts_count'] = self.get_object().posts.count()
        context['followers_count'] = self.get_object().followers.count()
        context['following_count'] = self.get_object().following.count()

        return context


class FollowView(LoginRequiredMixin, RedirectView):
    """
    Follow or unfollow a user.
    """
    pattern_name = 'users:detail'
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        username = kwargs['username']
        followee = get_object_or_404(User, username=username)
        follower = self.request.user

        # Check if the user is already following
        follow_exists = Follows.objects.filter(
            follower=follower,
            followee=followee,
        ).exists()

        if follow_exists:
            # If already following, unfollow
            Follows.objects.filter(
                follower=follower,
                followee=followee,
            ).delete()
        else:
            # If not following, follow
            Follows.objects.create(
                follower=follower,
                followee=followee,
            )

        return super().get_redirect_url(*args, **kwargs)

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static 'img/picscape.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>@{{ user.username }} | PicScape</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.picture.url }}" alt="@{{ user.username }}" class="rounded-circle" width="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                    
                        <a
                            href="{% url 'users:profile' %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                    
                        <a
                            href="{% url 'users:follow' user %}"
                            class="ml-5 btn btn-sm btn-primary"
                        >
                        {% if is_following %} 
                            Unfollow 
                        {% else %} 
                            Follow 
                        {% endif %}
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ posts_count }}</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ followers_count }}</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ following_count }}</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>
    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
                <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                    <a href="{% url 'posts:detail' post.pk %}" class="border">
                        <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>PicScape Sign in</title>
{% endblock%}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger">Username or password is not valid! </p>
    {% endif %}

    <form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username" name="username" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>


        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>

    </form>

    <p class="mt-4">Don't have an account yet? <a href="{% url 'users:signup' %}">Sign up here.</a></p>

{% endblock %}

templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">
            <form action="{% url 'users:profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class='media'>
                    {%if profile.picture %}
                    <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else %}
                    <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4"> @{{ user.username }} | {{ user.get_full_name }} </h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{error}}
                </div>
                {% endfor %}

                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input class="form-control {% if form.website.errors %} is-invalid {% endif %}" 
                        type="text"
                        name="website" 
                        placeholder="Website" 
                        value="{% if form.errors %}{{form.website.value}}{% else %}{{ profile.website }}{% endif %}" />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{error}}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    <textarea class="form-control {% if form.biography.errors %} is-invalid {% endif %}" 
                        type="text"
                        name="biography">{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>
                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{error}}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}" 
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.errors %}{{form.phone_number.value}}{% else %}{{ profile.phone_number }}{% endif %}"/>
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{error}}
                        {% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>PicScape Sign up</title>
{% endblock %}

{% block container %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Sign up!</button>

    </form>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profiles</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">
            <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}


                <div class='media'>
                    {%if profile.picture %}
                    <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else %}
                    <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4"> @{{ user.username }} | {{ user.get_full_name }} </h5>
                        <p class="ml-4"><input type="file" name="picture" required="true"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{error}}
                </div>
                {% endfor %}


                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input class="form-control {% if form.website.errors %} is-invalid {% endif %}" type="text"
                        name="website" placeholder="Website" {#si ocurre un error, igual muesstra el valor ingresado
                        --sino muestra el valor por defecto#}
                        value="{% if form.errors %} {{form.website.value}} {% else %} {{ profile.website }} {% endif %}" />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                        {{error}}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    {#si ocurre un error lo muestra#}
                    <textarea class="form-control {% if form.biography.errors %} is-invalid {% endif %}" type="text"
                        name="biography">{% if form.errors %} {{ form.biography.value }} {% else %} {{ profile.biography }} {% endif %}</textarea>
                    {#acá muestra el error dentro de div en un cuadro rojo, con la descipcion#}
                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                        {{error}}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}" type="text"
                        name="phone_number" {% if form.errors %} {{form.phone_number.value}} {% else %} {{
                        profile.phone_number }} {% endif %} placeholder="Phone number"
                        value="{{ profile.phone_number }}" />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                        {{error}}
                        {% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}